# -*- coding: utf-8 -*-
"""Mod_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11np5tgEiMJk2LZOAvaJeRr8u34U7xGuK
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

data = {
    "Назва книги": [
        "Гаррі Поттер і філософський камінь", "1984", "Маленький принц",
        "Війна і мир", "Код да Вінчі", "Мистецтво війни",
        "Дюна", "Пригоди Тома Сойєра", "Сто років самотності", "Хроніки Нарнії"
    ],
    "Жанр": [
        "Фентезі", "Драма", "Притча", "Історичний роман", "Детектив",
        "Філософія", "Фантастика", "Пригоди", "Магічний реалізм", "Фентезі"
    ],
    "Кількість сторінок": [320, 270, 100, 1225, 450, 200, 540, 210, 417, 280],
    "Вік читача": [15, 25, 12, 40, 30, 35, 20, 14, 28, 16],
    "Кількість прочитань": [5, 2, 6, 1, 3, 2, 3, 5, 2, 4],
    "Рейтинг": [4.9, 4.5, 4.8, 4.2, 4.6, 4.4, 4.7, 4.5, 4.3, 4.8]
}

df = pd.DataFrame(data)

df["Високий рейтинг"] = (df["Рейтинг"] >= 4.6).astype(int)

label_encoder = LabelEncoder()
df["Жанр_код"] = label_encoder.fit_transform(df["Жанр"])

X = df[["Жанр_код", "Кількість сторінок", "Вік читача", "Кількість прочитань"]]
y = df["Високий рейтинг"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

model = DecisionTreeClassifier(criterion="entropy", max_depth=3, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("\nЗвіт класифікації:")
print(classification_report(y_test, y_pred))

plt.figure(figsize=(12,6))
plot_tree(
    model,
    feature_names=X.columns,
    class_names=["Низький", "Високий"],
    filled=True,
    rounded=True
)
plt.title("Дерево рішень — прогноз рейтингу книг")
plt.show()

print("\nТаблиця даних 'Бібліотека':")
display(df)