# -*- coding: utf-8 -*-
"""Modul_3_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l_mgCyPXUhvgTB8E1Vs2L7Qjwm0I8rXp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score

data = {
    "Глюкоза": [3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0],
    "Гемоглобін": [118, 125, 132, 138, 142, 145, 147, 149, 150, 150]
}

df = pd.DataFrame(data)

coeffs = np.polyfit(df["Глюкоза"], df["Гемоглобін"], 2)
model = np.poly1d(coeffs)

y_pred = model(df["Глюкоза"])

r2 = r2_score(df["Гемоглобін"], y_pred)
print("Параметри моделі:", coeffs)
print(f"Коефіцієнт детермінації (R²): {r2:.3f}")

x_range = np.linspace(3.5, 8.0, 100)
plt.figure(figsize=(8, 5))
plt.scatter(df["Глюкоза"], df["Гемоглобін"], color="#4C9F70", s=80, label="Спостереження")
plt.plot(x_range, model(x_range), color="#2E7D32", linewidth=2.5, label="Нелінійна модель (2-й ступінь)")

plt.title("Нелінійна модель зв’язку між стабілізованою глюкозою та гемоглобіном", fontsize=13, weight="bold")
plt.xlabel("Стабілізована глюкоза (ммоль/л)")
plt.ylabel("Гемоглобін (г/л)")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()