# -*- coding: utf-8 -*-
"""Modul_2_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQRoqSIkE6UD5seGzDNnIzTVxqywaiMJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = {
    "Ліпопротеїни": [3.2, 4.1, 5.0, 3.8, 4.5, 5.3, 3.6, 4.8, 5.5, 4.0],
    "Гемоглобін": [120, 130, 140, 128, 135, 145, 125, 138, 150, 132]
}

df = pd.DataFrame(data)

r = df["Ліпопротеїни"].corr(df["Гемоглобін"])
print("Коефіцієнт кореляції між ліпопротеїнами та гемоглобіном:", round(r, 3))

plt.figure(figsize=(8, 5))
plt.style.use("seaborn-v0_8-whitegrid")

plt.scatter(
    df["Ліпопротеїни"], df["Гемоглобін"],
    color="#4C9F70", edgecolor="black", s=100, alpha=0.8, label="Спостереження"
)

z = np.polyfit(df["Ліпопротеїни"], df["Гемоглобін"], 1)
p = np.poly1d(z)
plt.plot(df["Ліпопротеїни"], p(df["Ліпопротеїни"]),
         color="#2E7D32", linewidth=2.5, label="Лінія тренду")

for i, txt in enumerate(df.index + 1):
    plt.text(df["Ліпопротеїни"][i] + 0.02, df["Гемоглобін"][i] + 0.5, f"№{txt}", fontsize=9)

plt.title("Залежність між рівнем ліпопротеїнів і гемоглобіну", fontsize=14, weight="bold", pad=15)
plt.xlabel("Рівень ліпопротеїнів (ммоль/л)", fontsize=12)
plt.ylabel("Рівень гемоглобіну (г/л)", fontsize=12)
plt.legend(frameon=True, shadow=True)
plt.tight_layout()
plt.show()