# -*- coding: utf-8 -*-
"""modul_4_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dXyOP6Un7C5Q8eGqxRIgiUbs3xwIrFX
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

data = {
    "Жанр": [
        "Фентезі", "Драма", "Притча", "Історичний роман", "Детектив",
        "Філософія", "Фантастика", "Пригоди", "Магічний реалізм", "Фентезі"
    ],
    "Кількість сторінок": [320, 270, 100, 1225, 450, 200, 540, 210, 417, 280],
    "Вік читача": [15, 25, 12, 40, 30, 35, 20, 14, 28, 16],
    "Кількість прочитань": [5, 2, 6, 1, 3, 2, 3, 5, 2, 4],
    "Рейтинг": [4.9, 4.5, 4.8, 4.2, 4.6, 4.4, 4.7, 4.5, 4.3, 4.8]
}

df = pd.DataFrame(data)

le = LabelEncoder()
df["Жанр_код"] = le.fit_transform(df["Жанр"])

X = df[["Жанр_код", "Кількість сторінок", "Вік читача", "Кількість прочитань"]]
y = df["Рейтинг"]

model = LinearRegression()
model.fit(X, y)

coefficients = pd.DataFrame({
    "Змінна": X.columns,
    "Коефіцієнт": model.coef_
})

intercept = model.intercept_
r2 = r2_score(y, model.predict(X))

print("\nКоефіцієнт детермінації R² =", round(r2, 3))
print("\nВплив змінних:")
display(coefficients)

plt.figure(figsize=(8, 5))
plt.plot(y.values, label="Реальні значення", marker="o")
plt.plot(model.predict(X), label="Прогноз моделі", marker="s")
plt.title("Порівняння фактичних і прогнозних рейтингів книг", fontsize=13, weight="bold")
plt.xlabel("Номер книги")
plt.ylabel("Рейтинг")
plt.legend()
plt.grid(alpha=0.5)
plt.show()